name: vigilio_app
description: MVP 1 do VigilioApp
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/Button.png
    - assets/banner.png
    - assets/Detail.png
    - assets/Fala_Home.png
    - assets/Fala_Config.png
    - assets/Background.png
    - assets/Return_Button.png
    - assets/Banner_Home.png